title: Spook Limited
email: enquiries@spook.co.uk 
description: >- # this means to ignore newlines until "baseurl:"
  Spook are industry leaders in remote monitoring. Book your online demo today.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections_dir: collections

sass:
  style: compressed