- name: Temperature
  icon: /images/sensor/icons/temperature.svg
  link: /monitoring/environmental/temperature

- name: Humidity
  icon: /images/sensor/icons/humidity.svg
  link: /monitoring/environmental/humidity

- name: Dew point
  icon: /images/sensor/icons/dewpoint.svg
  link: /monitoring/environmental/dewpoint

- name: Water
  icon: /images/sensor/icons/water.svg
  link: /monitoring/environmental/water

- name: Air flow
  icon: /images/sensor/icons/airflow.svg
  link: /monitoring/environmental/airflow
